
[env]
TERM = "xterm-256color"

[font]
size = 12.0
builtin_box_drawing = true

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u000D"
key = "NumpadEnter"

# change option key behavior
# [[keyboard.bindings]]
# key = "Left"
# mods = "Alt"
# action = "Left"

# [[keyboard.bindings]]
# key = "Right"
# mods = "Alt"
# action = "Right"


[terminal.shell]
args = ["-l", "-c", "tmux new -A"]
program = "/bin/zsh"

[window]
decorations = "None"
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[general]
# alphabet = "jfkdls;ahgurieowpq"
import = [
  # "~/.dracula-alacritty/dracula.toml"]
#
# uncomment the flavour you want below:
# "~/.config/alacritty/catppuccin-latte.toml"
# "~/.config/alacritty/catppuccin-frappe.toml"
# "~/.config/alacritty/catppuccin-macchiato.toml"
 "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
